// axios로 API 통신하는 함수들
export async function getProducts() {
  return [
    {
      id: 1,
      name: 'ORUMM 콜렉터스팬츠_애쉬스톤',
      price: 125000,
      beforePrice: '',
      description: '힙한 아웃도어 스타일링을 완성해주는 ORUMM의 베스트셀링 팬츠',
      image: '01orumpants1.jpg',
      hoverImage: '01orumpants1-2.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 2,
      name: 'ORUMM 콜렉터스팬츠_블랙스톤',
      price: '125000',
      beforePrice: '',
      description: '힙한 아웃도어 스타일링을 완성해주는 ORUMM의 베스트셀링 팬츠',
      image: '02orumpants2.jpg',
      hoverImage: '02orumpants2-2.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 3,
      name: 'PUCO 썸머 페이즐리 드레스',
      price: '84000',
      beforePrice: '',
      description:
        '여름 바람처럼 가볍게 흐르는, 빈티지 무드의 맥시 페이즐링 스트링 원피스(2colors)',
      image: '03paiseley1.jpg',
      hoverImage: '03paiseley1-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: true,
    },
    {
      id: 4,
      name: 'PUCO 강연 베이직 티',
      price: '39000',
      beforePrice: '',
      description: '고퀄리티 강연면 원단의 참된 편함을 전할 스탠다드핏 반팔 티셔츠(7colors',
      image: '04pucobasict.jpg',
      hoverImage: '04pucobasict-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 5,
      name: 'PUCO 오프바운드 슬리브리스',
      price: '37000',
      beforePrice: '',
      description:
        '힙을 덮는 언발라스 기장, 편안하고 세련된 여름 코디의 완성! 언발란스 슬리브리스 탑(5colors)',
      image: '05pucooffbound.jpg',
      hoverImage: '05pucooffbound-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: true,
    },
    {
      id: 6,
      name: 'PUCO 썸머레이스 조끼',
      price: '54000',
      beforePrice: '',
      description: '여름 탑 위에 가볍게 걸치기 좋은 통기성 좋은 레이스 조끼(3colors)',
      image: '06pucosummerlace.jpg',
      hoverImage: '06pucosummerlace-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 7,
      name: 'PUCO 에어코튼 티셔츠',
      price: '39000',
      beforePrice: '',
      description: '슬라브와 직기 배색이 돋보이는 PUCO의 스타일리시한 티셔츠(4colors)',
      image: '07pucoaircotton.jpg',
      hoverImage: '07pucoaircotton-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 8,
      name: 'PUCO 에어코튼 팬츠',
      price: '66000',
      beforePrice: '',
      description: '슬라브와 직기 배색이 돋보이는 PUCO의 네추럴 썸머 팬츠(3colors)',
      image: '08pucoaircottonpants.jpg',
      hoverImage: '08pucoaircottonpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 9,
      name: 'PUCO 린넨 차이나 셔츠',
      price: '118000',
      beforePrice: '',
      description: '천연 린넨 100%, 여름을 위한 최고의 푸코 셔츠(6colors)',
      image: '09pucolinenchina.jpg',
      hoverImage: '09pucolinenchina-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 10,
      name: 'PUCO 에브리데이 슬라브 V넥 티',
      price: '29000',
      beforePrice: '',
      description: '구름결처럼 부드러운 터치, 여름을 위한 PUCO의 워싱 슬라브 V넥 티셔츠(4colors)',
      image: '10pucoeverydayvneck.jpg',
      hoverImage: '10pucoeverydayvneck-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 11,
      name: 'PUCO 에브리데이 7부 팬츠',
      price: '69000',
      beforePrice: '',
      description: '툭 떨어지는 실루엣, 체형 커버에도 좋은 여름용 PUCO의 짧은 팬츠(6colors)',
      image: '11pucoeverydaypants.jpg',
      hoverImage: '11pucoeverydaypants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 12,
      name: 'PUCO 디에센셜 슬리브리스 티',
      price: '23800',
      beforePrice: '34800',
      description:
        '차분한 피그먼트 컬러와 부드러운 착용감, 어깨서ㅓㄴ을 감싸는 오버핏 실루엣으로 자연스럽게 멋스러운 여름 데일리 슬리브리스(3colors)',
      image: '12clear_pucoessentialsleeveless.jpg',
      hoverImage: '12clear_pucoessentialsleeveless-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: true,
      percentage: '30',
      best: false,
    },
    {
      id: 13,
      name: 'PUCO 린넨 와이드 팬츠',
      price: '63200',
      beforePrice: '79000',
      description: '9부 기장의 여유로운 핏, 일상과 여행에 모두 잘 어울리는 PUCO 린넨 팬츠(4colors)',
      image: '13clear_pucolinenwidepants.jpg',
      hoverImage: '13clear_pucolinenwidepants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: true,
      percentage: '20',
      best: false,
    },
    {
      id: 14,
      name: 'PUCO 슬라브 치마바지',
      price: '65000',
      beforePrice: '',
      description: '프리미엄 면 소재로 편안함이 남다른 푸코의 와이드핏 치마바지(3colors)',
      image: '14pucoskirtpants.jpg',
      hoverImage: '14pucoskirtpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 15,
      name: 'PUCO 강연순면 슬리브리스 티',
      price: '36000',
      beforePrice: '',
      description: '퀄리티 있는 소재로 완성된 깔끔한 푸코의 여름 이너/단독 민소매 티셔츠(7colors)',
      image: '15pucopurecottonT.jpg',
      hoverImage: '15pucopurecottonT-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 16,
      name: 'PCUO 핀탁 썸머팬츠',
      price: '72000',
      beforePrice: '',
      description:
        '심플하지만 감각적인 밑단 핀턱 디테일, 착용감까지 가벼운 푸코의 여름팬츠(3colors)',
      image: '16pucopintucksummerpants.jpg',
      hoverImage: '16pucopintucksummerpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 17,
      name: 'PUCO 디에센셜 루즈핏 반팔티',
      price: '31200',
      beforePrice: '39000',
      description:
        '레이아스가 애정하는 로컬브랜드 PUCO에서 준비한 은은한 컬러감과 배색 스티치로 멋을 더한 감성 오버핏 티셔츠(3colors)',
      image: '17clear_pucoessentialloosefitT.jpg',
      hoverImage: '17clear_pucoessentialloosefitT-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: true,
      percentage: '20',
      best: false,
    },
    {
      id: 18,
      name: 'PUCO 데일리 플레어 팬츠',
      price: '94000',
      beforePrice: '',
      description:
        '부드럽게 흐르는 플레어 실루엣, 편안함 속의 감성 미학, 푸코의 플레어 팬츠(3colors)',
      image: '18pucodailyflairpants.jpg',
      hoverImage: '18pucodailyflairpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 19,
      name: 'PUCO 시그니처 코튼 롱 드레스',
      price: '59000',
      beforePrice: '',
      description: '어떤 날에도 가볍게 입고 나설 수 있는, 감각적인 여름 한 벌(2colors)',
      image: '19pucocottonlongonepiece.jpg',
      hoverImage: '19pucocottonlongonepiece-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 20,
      name: 'PUCO lettesr Tee',
      price: '39000',
      beforePrice: '',
      description:
        '프리미엄 30수 오가닉코튼에 레어 워싱으로 담아낸 부드러운 색감, 여름을 위한 섬세한 티셔츠(5colors)',
      image: '20pucolettersT.jpg',
      hoverImage: '20pucolettersT-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 21,
      name: 'PUCO 오가닉코튼 슬리브리스',
      price: '29000',
      beforePrice: '',
      description: '기본을 가장 정성스럽게 만든, 푸코의 감각적인 슬리브리스(3colors)',
      image: '21pucoorganiccottonsleeveless.jpg',
      hoverImage: '21pucoorganiccottonsleeveless-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 22,
      name: '온 더 웨이_머스타드',
      price: '35000',
      beforePrice: '',
      description:
        '오름의 상상력과 일러스트레이터 은작가님의 터치가 만나 탄생한 특별한 오가닉 티셔츠',
      image: '22orumTorange.jpg',
      hoverImage: '22orumTorange-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 23,
      name: '온 더 웨이_블랙',
      price: '35000',
      beforePrice: '',
      description:
        '오름의 상상력과 일러스트레이터 은작가님의 터치가 만나 탄생한 특별한 오가닉 티셔츠',
      image: '23orumTblack.jpg',
      hoverImage: '23orumTblack-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 24,
      name: '온 더 웨이_스카이',
      price: '35000',
      beforePrice: '',
      description:
        '오름의 상상력과 일러스트레이터 은작가님의 터치가 만나 탄생한 특별한 오가닉 티셔츠',
      image: '24orumTsky.jpg',
      hoverImage: '24orumTsky-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
    },
  ]
}
