export async function getProducts() {
  return [
    {
      id: 1,
      name: 'Backstage 데일리 사코슈 백',
      price: 29000,
      beforePrice: '',
      description:
        '여행과 일상 그 어느 상황에도 잘 어울리는 파라루프 원단의 스타일리시 소형 사코슈(2colors)',
      image: '01bag.jpg',
      hoverImage: '01-2bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: true,
    },
    {
      id: 2,
      name: 'Backstage 데일리 숄더백 12L',
      price: 56000,
      beforePrice: '',
      description: '노트북 수납부터 여행까지, 12L 넉넉한 용량의 경량 숄더백(2colors)',
      image: '02thai_bag.jpg',
      hoverImage: '02-2thai_bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
    },
    {
      id: 3,
      name: 'Backstage 익스플로러 사코슈 백',
      price: 38000,
      beforePrice: '',
      description:
        '여행과 일상 그 어느 상화아에도 잘 어울리는 고기능성 원단의 스타일리시 중형 사코슈 백(2colors)',
      image: '02thai_bag.jpg',
      hoverImage: '02-2thai_bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
    },
  ]
}
