export async function getAllProducts() {
  return [
    {
      id: 1,
      name: '지중해식 가지&새우 감바스(280g)',
      price: '10450',
      beforePrice: '11000',
      description:
        '지중해의 여유와 풍요로움을 담아 좋ㅇ은 식재료로 만든 제대로 된 감바스 소개해요(냉장)',
      image: '01summerdish.jpg',
      hoverImage: '01-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'maindish',
      clearance: false,
      percentage: '5',
      best: false,
      new: true,
      newSaleDate: '',
    },
    {
      id: 2,
      name: '네팔리 다밧을 오마주한 치킨커리(400/700g)',
      price: '9000',
      beforePrice: '',
      description:
        '수년이 지나도 생각나는 정결한 정찬 네발리 달밧을 우리 입맛에 잘 맞는 치킨 커리로 재해석해 만든 특별한 요리(냉동)',
      image: '01maindish.jpg',
      hoverImage: '01-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 3,
      name: '쁠라무 꿍팟 퐁커리(2~3인분)',
      price: '23800',
      beforePrice: '',
      description:
        '부드러운 계란 커리와 해산물의 조화, 따뜻하게 데워 밥 위에 쓱쓱! 집에서 즐기는 호불호 없는 퓨전 태국커리 700g(냉동)',
      image: '02maindish.jpg',
      hoverImage: '02-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 4,
      name: '프렌치 토마트&비프 스튜(2인분)',
      price: '14800',
      beforePrice: '',
      description:
        '진하게 우려낸 토마토 소스에 부드러운 소고기와 신선채소를 듬뿍 넣어 끓여낸 영양만점! 프랑스 가정식 요리 440g(냉동)',
      image: '03maindish.jpg',
      hoverImage: '03-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 5,
      name: '올인원 한끼 플레이트(1~2인분)',
      price: '5800',
      beforePrice: '',
      description:
        '존슨빌 소세지, 야채믹스, 후무스를 한 번에! 완벽한 영양 균형의 한 끼 플레이트 350g(냉동)',
      image: '04maindish.jpg',
      hoverImage: '04-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 6,
      name: '대만식 마늘쫑 돼지고기 볶음(2인분)',
      price: '7500',
      beforePrice: '',
      description:
        '아삭한 마늘쫑과 감칠맛 가득한 돼지고기가 레이아만의 특별한 레시피로 환상의 앙상블을 이루는 대만식 볶음 요리(냉동)',
      image: '05maindish.jpg',
      hoverImage: '05-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 7,
      name: 'Polve a la Casa - 포르투갈식 문어요리(1~2인분)',
      price: '25800',
      beforePrice: '',
      description:
        '포르투에서 접한 감동의 맛을 재현하고 싶었어요. 정성껏 만든 포르투갈식 문어요리를 소개해요! 340g(냉장)',
      image: '06maindish.jpg',
      hoverImage: '06-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 8,
      name: '일본식 돼지고기 동파육(1~2인분)',
      price: '18800',
      beforePrice: '',
      description:
        '진하게 졸여 부드럽게 녹아드는 일본식 통삼겹. 연겨자 한 점 곁드이면 완벽한 한 끼 완성! 300g(냉장)',
      image: '07maindish.jpg',
      hoverImage: '07-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 9,
      name: '이탈리안 토마토 라구 파스타(1~2인분)',
      price: '13800',
      beforePrice: '',
      description:
        '정통 이탈리아 식으로 완성한, 익숙한 듯 특별하고 속이 든든해지는 무첨가, 무방부제 토마토&미트 라구 파스타 400g(냉동)',
      image: '08maindish.jpg',
      hoverImage: '08-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 10,
      name: '이탈리안 화이트 라구 파스타(1~2인분)',
      price: '13800',
      beforePrice: '',
      description:
        '정통 이탈리아 식으로 완성한, 익숙한 듯 특별하고 속이 든든해지는 무첨가, 무방부제 크림&미트 라구 파스타 400g(냉동)',
      image: '09maindish.jpg',
      hoverImage: '09-2maindish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'maindish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 11,
      name: '한우소고기 볶음 고추장(280g)',
      price: '13300',
      beforePrice: '14000',
      description:
        '비빔밥, 주막밥, 쌈밥은 물론 비빔국수에도 딱 어울리는 집에 하나쯤 꼭 있어야 할 진짜 만능고추장(냉장)',
      image: '01sidedish.jpg',
      hoverImage: '01-2sidedish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'sidedish',
      clearance: false,
      percentage: '5',
      best: true,
      new: true,
      newSaleDate: '',
    },
    {
      id: 11,
      name: '레이아의 오이 물김치(350/700g)',
      price: '4000',
      beforePrice: '',
      description: '여름 식탁을 시원하게 채워줄 아삭하고 청량한 오이 물김치(냉장)',
      image: '03summerdish.jpg',
      hoverImage: '03-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'sidedish',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 12,
      name: '토마토 츠케모노&시키타시(600g)',
      price: '5500',
      beforePrice: '',
      description:
        '입맛을 깨워주는, 이 계절의 가장 상큼한 한 입! 유자&간장베이스 냉토마토 조림(냉장)',
      image: '04summerdish.jpg',
      hoverImage: '04-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'sidedish',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 13,
      name: '레이아의 오이소박이(600g/1kg)',
      price: '6000',
      beforePrice: '',
      description:
        '17년 집밥경력 레이아의 자신만만 레시피와 국산 신선채소로 정성다해 완성한 여름날 최고의 밑반찬(냉장)',
      image: '05summerdish.jpg',
      hoverImage: '05-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'sidedish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 14,
      name: '레이아의 모듬피클(420/700g)',
      price: '5800',
      beforePrice: '',
      description:
        '국산의 신선한 채소로 정성껏 담근, 매일 꺼내먹고 싶은 산뜻한 아삭함의 모듬 피클(2size)(냉장)',
      image: '06summerdish.jpg',
      hoverImage: '06-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'sidedish',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 15,
      name: '스웨디시 미트볼&토마토라구 소스(2인분)',
      price: '11000',
      beforePrice: '',
      description:
        '든듣ㄴ하고 풍성한 한 끼가 필요할 때! 파스타도 덮밥도 빵과도 찰떡궁합인 매력적인 만능소스 440g(냉동)',
      image: '02sidedish.jpg',
      hoverImage: '02-2sidedish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: false,
      category: 'sidedish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 16,
      name: '레몬 간장 연어장(1~2인분)',
      price: '13800',
      beforePrice: '',
      description:
        '신선한 노르웨이산 생연어를 701간장 베이스에 절여 레몬의 산뜻함과 고추의 알싸함을 더한 프리미엄 연어장 250g(냉장)',
      image: '07summerdish.jpg',
      hoverImage: '07-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'sidedish',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 17,
      name: '레이아의 시그니처 소고기 장조림(500g)',
      price: '13800',
      beforePrice: '',
      description: '한 끼 식사를 책임 질 고단백 소고기 홍두깨살 수제 장조림(냉장)',
      image: '08summerdish.jpg',
      hoverImage: '08-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'sidedish',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 18,
      name: 'ELJADE 1100% 수박착즙 프리미엄 주스',
      price: '3500',
      beforePrice: '',
      description:
        '코스트코 수박주스로 유명한 100& 수박 착즙주스! 맛과 영양성분 고스란히 살린 HPP공법으로 완성된 프리미엄 주스',
      image: '02summerdish.jpg',
      hoverImage: '02-2summerdish.jpg',
      brand: '',
      isThai: false,
      isSummerdish: true,
      category: 'desert',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 18,
      name: 'Kewpie 트러플마요 90g',
      price: '5000',
      beforePrice: '',
      description: '은은한 트러플의 풍미, 고급스러운 마요의 변신!',
      image: '03thai.jpg',
      hoverImage: '03-2thai.jpg',
      brand: '',
      isThai: true,
      isSummerdish: false,
      category: 'foodit',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 19,
      name: 'Mama 쉬림프 똠얌 죽',
      price: '1000',
      beforePrice: '',
      description:
        '매콤한 똠얌의 진한 풍미를 그대로 담은 태국식 즉석 쉬림프 죽. 뜨거운 물만 부으면 2분 만에 완성되는 간편한 이국적인 한 끼',
      image: '07thai.jpg',
      hoverImage: '07-2thai.jpg',
      brand: '',
      isThai: true,
      isSummerdish: false,
      category: 'foodit',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 20,
      name: '인스턴트 밀크 그린티 5개 set',
      price: '4500',
      beforePrice: '',
      description:
        '녹차의 깊은 향과 부드러운 우유가 어우러진 녹차라떼. 3 in 1으로 언제 어디서나 간편하게 즐기는 달콤 향긋한 티타임',
      image: '08thai.jpg',
      hoverImage: '08-2thai.jpg',
      brand: '',
      isThai: true,
      isSummerdish: false,
      category: 'foodit',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 21,
      name: '인스턴트 밀크티 5개 set',
      price: '4500',
      beforePrice: '',
      description:
        '진한 홍차와 달콤한 밀크가 어우러진 타이 밀크티. 3 in 1으로 언제 어디서나 간편하게 즐기는 달콤 향긋한 티타임',
      image: '09thai.jpg',
      hoverImage: '09-2thai.jpg',
      brand: '',
      isThai: true,
      isSummerdish: false,
      category: 'foodit',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
  ]
}
