// 메뉴2 api
// import { getProducts as getApparel } from './apparel'
// import { getProducts as getBag } from './bag'
// import { getProducts as getFashion } from './fashion'

export async function getAllProducts() {
  return [
    // 의류
    {
      id: 1,
      name: 'ORUMM 콜렉터스팬츠_애쉬스톤',
      price: '125000',
      beforePrice: '',
      description: '힙한 아웃도어 스타일링을 완성해주는 ORUMM의 베스트셀링 팬츠',
      image: '01orumpants1.jpg',
      hoverImage: '01orumpants1-2.jpg',
      brand: 'orrumm',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 2,
      name: 'ORUMM 콜렉터스팬츠_블랙스톤',
      price: '125000',
      beforePrice: '',
      description: '힙한 아웃도어 스타일링을 완성해주는 ORUMM의 베스트셀링 팬츠',
      image: '02orumpants2.jpg',
      hoverImage: '02orumpants2-2.jpg',
      brand: 'orrumm',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 3,
      name: 'PUCO 썸머 페이즐리 드레스',
      price: '84000',
      beforePrice: '',
      description:
        '여름 바람처럼 가볍게 흐르는, 빈티지 무드의 맥시 페이즐링 스트링 원피스(2colors)',
      image: '03paiseley1.jpg',
      hoverImage: '03paiseley1-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 4,
      name: 'PUCO 강연 베이직 티',
      price: '39000',
      beforePrice: '',
      description: '고퀄리티 강연면 원단의 참된 편함을 전할 스탠다드핏 반팔 티셔츠(7colors',
      image: '04pucobasict.jpg',
      hoverImage: '04pucobasict-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 5,
      name: 'PUCO 오프바운드 슬리브리스',
      price: '37000',
      beforePrice: '',
      description:
        '힙을 덮는 언발라스 기장, 편안하고 세련된 여름 코디의 완성! 언발란스 슬리브리스 탑(5colors)',
      image: '05pucooffbound.jpg',
      hoverImage: '05pucooffbound-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 6,
      name: 'PUCO 썸머레이스 조끼',
      price: '54000',
      beforePrice: '',
      description: '여름 탑 위에 가볍게 걸치기 좋은 통기성 좋은 레이스 조끼(3colors)',
      image: '06pucosummerlace.jpg',
      hoverImage: '06pucosummerlace-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 7,
      name: 'PUCO 에어코튼 티셔츠',
      price: '39000',
      beforePrice: '',
      description: '슬라브와 직기 배색이 돋보이는 PUCO의 스타일리시한 티셔츠(4colors)',
      image: '07pucoaircotton.jpg',
      hoverImage: '07pucoaircotton-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 8,
      name: 'PUCO 에어코튼 팬츠',
      price: '66000',
      beforePrice: '',
      description: '슬라브와 직기 배색이 돋보이는 PUCO의 네추럴 썸머 팬츠(3colors)',
      image: '08pucoaircottonpants.jpg',
      hoverImage: '08pucoaircottonpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 9,
      name: 'PUCO 린넨 차이나 셔츠',
      price: '118000',
      beforePrice: '',
      description: '천연 린넨 100%, 여름을 위한 최고의 푸코 셔츠(6colors)',
      image: '09pucolinenchina.jpg',
      hoverImage: '09pucolinenchina-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 10,
      name: 'PUCO 에브리데이 슬라브 V넥 티',
      price: '29000',
      beforePrice: '',
      description: '구름결처럼 부드러운 터치, 여름을 위한 PUCO의 워싱 슬라브 V넥 티셔츠(4colors)',
      image: '10pucoeverydayvneck.jpg',
      hoverImage: '10pucoeverydayvneck-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 11,
      name: 'PUCO 에브리데이 7부 팬츠',
      price: '69000',
      beforePrice: '',
      description: '툭 떨어지는 실루엣, 체형 커버에도 좋은 여름용 PUCO의 짧은 팬츠(6colors)',
      image: '11pucoeverydaypants.jpg',
      hoverImage: '11pucoeverydaypants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 12,
      name: 'PUCO 디에센셜 슬리브리스 티',
      price: '23800',
      beforePrice: '34800',
      description:
        '차분한 피그먼트 컬러와 부드러운 착용감, 어깨서ㅓㄴ을 감싸는 오버핏 실루엣으로 자연스럽게 멋스러운 여름 데일리 슬리브리스(3colors)',
      image: '12clear_pucoessentialsleeveless.jpg',
      hoverImage: '12clear_pucoessentialsleeveless-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: true,
      percentage: '30',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 13,
      name: 'PUCO 린넨 와이드 팬츠',
      price: '63200',
      beforePrice: '79000',
      description: '9부 기장의 여유로운 핏, 일상과 여행에 모두 잘 어울리는 PUCO 린넨 팬츠(4colors)',
      image: '13clear_pucolinenwidepants.jpg',
      hoverImage: '13clear_pucolinenwidepants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 14,
      name: 'PUCO 슬라브 치마바지',
      price: '65000',
      beforePrice: '',
      description: '프리미엄 면 소재로 편안함이 남다른 푸코의 와이드핏 치마바지(3colors)',
      image: '14pucoskirtpants.jpg',
      hoverImage: '14pucoskirtpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 15,
      name: 'PUCO 강연순면 슬리브리스 티',
      price: '36000',
      beforePrice: '',
      description: '퀄리티 있는 소재로 완성된 깔끔한 푸코의 여름 이너/단독 민소매 티셔츠(7colors)',
      image: '15pucopurecottonT.jpg',
      hoverImage: '15pucopurecottonT-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 16,
      name: 'PCUO 핀탁 썸머팬츠',
      price: '72000',
      beforePrice: '',
      description:
        '심플하지만 감각적인 밑단 핀턱 디테일, 착용감까지 가벼운 푸코의 여름팬츠(3colors)',
      image: '16pucopintucksummerpants.jpg',
      hoverImage: '16pucopintucksummerpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 17,
      name: 'PUCO 디에센셜 루즈핏 반팔티',
      price: '31200',
      beforePrice: '39000',
      description:
        '레이아스가 애정하는 로컬브랜드 PUCO에서 준비한 은은한 컬러감과 배색 스티치로 멋을 더한 감성 오버핏 티셔츠(3colors)',
      image: '17clear_pucoessentialloosefitT.jpg',
      hoverImage: '17clear_pucoessentialloosefitT-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 18,
      name: 'PUCO 데일리 플레어 팬츠',
      price: '94000',
      beforePrice: '',
      description:
        '부드럽게 흐르는 플레어 실루엣, 편안함 속의 감성 미학, 푸코의 플레어 팬츠(3colors)',
      image: '18pucodailyflairpants.jpg',
      hoverImage: '18pucodailyflairpants-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 19,
      name: 'PUCO 시그니처 코튼 롱 드레스',
      price: '59000',
      beforePrice: '',
      description: '어떤 날에도 가볍게 입고 나설 수 있는, 감각적인 여름 한 벌(2colors)',
      image: '19pucocottonlongonepiece.jpg',
      hoverImage: '19pucocottonlongonepiece-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 20,
      name: 'PUCO lettesr Tee',
      price: '39000',
      beforePrice: '',
      description:
        '프리미엄 30수 오가닉코튼에 레어 워싱으로 담아낸 부드러운 색감, 여름을 위한 섬세한 티셔츠(5colors)',
      image: '20pucolettersT.jpg',
      hoverImage: '20pucolettersT-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 21,
      name: 'PUCO 오가닉코튼 슬리브리스',
      price: '29000',
      beforePrice: '',
      description: '기본을 가장 정성스럽게 만든, 푸코의 감각적인 슬리브리스(3colors)',
      image: '21pucoorganiccottonsleeveless.jpg',
      hoverImage: '21pucoorganiccottonsleeveless-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 22,
      name: '온 더 웨이_머스타드',
      price: '35000',
      beforePrice: '',
      description:
        '오름의 상상력과 일러스트레이터 은작가님의 터치가 만나 탄생한 특별한 오가닉 티셔츠',
      image: '22orumTorange.jpg',
      hoverImage: '22orumTorange-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 23,
      name: '온 더 웨이_블랙',
      price: '35000',
      beforePrice: '',
      description:
        '오름의 상상력과 일러스트레이터 은작가님의 터치가 만나 탄생한 특별한 오가닉 티셔츠',
      image: '23orumTblack.jpg',
      hoverImage: '23orumTblack-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 24,
      name: '온 더 웨이_스카이',
      price: '35000',
      beforePrice: '',
      description:
        '오름의 상상력과 일러스트레이터 은작가님의 터치가 만나 탄생한 특별한 오가닉 티셔츠',
      image: '24orumTsky.jpg',
      hoverImage: '24orumTsky-2.jpg',
      brand: 'puco',
      isThai: false,
      category: 'apparel',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    // 가방
    {
      id: 25,
      name: 'Backstage 데일리 사코슈 백',
      price: '29000',
      beforePrice: '',
      description:
        '여행과 일상 그 어느 상황에도 잘 어울리는 파라루프 원단의 스타일리시 소형 사코슈(2colors)',
      image: '01bag.jpg',
      hoverImage: '01-2bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 26,
      name: 'Backstage 데일리 숄더백 12L',
      price: '56000',
      beforePrice: '',
      description: '노트북 수납부터 여행까지, 12L 넉넉한 용량의 경량 숄더백(2colors)',
      image: '02thai_bag.jpg',
      hoverImage: '02-2thai_bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 27,
      name: 'Backstage 익스플로러 사코슈 백',
      price: '38000',
      beforePrice: '',
      description:
        '여행과 일상 그 어느 상화아에도 잘 어울리는 고기능성 원단의 스타일리시 중형 사코슈 백(2colors)',
      image: '03thai_bag.jpg',
      hoverImage: '03-2thai_bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 28,
      name: 'Backstage 디에이 스퀘어 숄더백',
      price: '29000',
      beforePrice: '',
      description: '꼭 필요한 것만 담는 하루, 무심한 듯 가볍게 매는 데일리 숄더백(2colors)',
      image: '04thai_bag.jpg',
      hoverImage: '04-2thai_bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 29,
      name: 'Backstage 크로스&쇼퍼 하이브리드 백',
      price: '43000',
      beforePrice: '',
      description:
        '꼭 필요한 순간, 꼭 필요한 만큼, 접히고 펼쳐지는 미니크로스&쇼퍼 2-in-1백(2colors)',
      image: '05thai_bag.jpg',
      hoverImage: '05-2thai_bag.jpg',
      brand: 'backstage',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 30,
      name: 'Hamblepie Little Basket_Peace&Joy',
      price: '46000',
      beforePrice: '',
      description: '"평화와 기쁨"이란 메시지와 자수 아트워크를 담은 감성 가득한 숄더백',
      image: '06bag.jpg',
      hoverImage: '06-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 31,
      name: 'Hamblepie 웬드 백',
      price: '78000',
      beforePrice: '',
      description:
        '방콕의 아이코닉 크래프트 브랜드 Hamblepie의 베스트 셀러 WIND시리지으 최신판 WEND BAG',
      image: '07bag.jpg',
      hoverImage: '07-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 32,
      name: 'Hamblepie 캐주얼 토트백',
      price: '56000',
      beforePrice: '',
      description:
        '방콕의 아이코닉 크래픝 브랜드 Hamblepie의 순수한 아이보리 색 오가닉 코튼의 심플자수 토트 백',
      image: '08bag.jpg',
      hoverImage: '08-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 33,
      name: 'Hamblepie Big Tote_Family',
      price: '56000',
      beforePrice: '',
      description:
        '햄블파이만의 감성으로 샌디의 아지트를 자수 아트워크로 담아낸 오가닉코튼 빅 토트백',
      image: '09bag.jpg',
      hoverImage: '09-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 34,
      name: 'Hamblepie Best bag',
      price: '69000',
      beforePrice: '',
      description:
        '컬러풀한 비즈와 자수 아트워크로 완성한 세상 둘도 없는 감각적 핸드크래프트 숄더백',
      image: '10bag.jpg',
      hoverImage: '10-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 35,
      name: 'Hamblepie Blacktrack_Picnic L',
      price: '84000',
      beforePrice: '',
      description: '다양한 자연 자수를 감각적으로 더한 블랙의 반원통형 숄더 백',
      image: '11bag.jpg',
      hoverImage: '11-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 36,
      name: 'Hamblepie Pocket in Hand gang',
      price: '29000',
      beforePrice: '',
      description:
        '4가지 유쾌한 테마로 만나는 햄블파이 가마성 미니 파우치, 손에 꼭 쥐고 싶은 컬렉션',
      image: '12bag.jpg',
      hoverImage: '12-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 37,
      name: 'Hamblepie 미니 파우치',
      price: '29000',
      beforePrice: '',
      description: '자연을 모티브로 한 감성 자수 디자인의 햄블파이의 리미티드 미니 파우치 백 4종',
      image: '13bag.jpg',
      hoverImage: '13-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 38,
      name: 'Hamblepie PALS 피크닉 백_CREAM',
      price: '68000',
      beforePrice: '',
      description: '세상 모든 예쁜 강아지들을 햄블파이만의 자수로 담아 낸 핸드메이드 반원통 가방',
      image: '14bag.jpg',
      hoverImage: '14-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 39,
      name: 'Hamblepie PALS 피크닉 백_SOFT MINT',
      price: '68000',
      beforePrice: '',
      description: '세상 모든 예쁜 강아지들을 햄블파이만의 자수로 담아 낸 핸드메이드 반원통 가방',
      image: '15bag.jpg',
      hoverImage: '15-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 40,
      name: 'Hamblepie Blacktrack_Bottle',
      price: '49000',
      beforePrice: '',
      description:
        '즐거움이 함께 할 매 순간 함께 할 실용적인 사이즈와 캐주얼한 디자인의 블랙 보틀 백',
      image: '16bag.jpg',
      hoverImage: '16-2bag.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 41,
      name: 'Hmong 핸드메이드 빈티지 숄더백',
      price: '62300',
      beforePrice: '89000',
      description:
        '세상 단 하나뿐인 예술작품과도 같은 칸타퀼팅 팬드메이드 에스닉맥(Only 3 objects)',
      image: '17bag.jpg',
      hoverImage: '17-2bag.jpg',
      brand: 'Hmong',
      isThai: true,
      category: 'bag',
      clearance: true,
      percentage: '30',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 42,
      name: '메홍손 헨드퀼트 코튼백',
      price: '27300',
      beforePrice: '39000',
      description:
        '정갈한 스티치 위에 전통적인 에스닉 무드가 담긴 메홍손 카렌족의 핸드메이드 퀼팅백(3colors)',
      image: '18bag.jpg',
      hoverImage: '18-2bag.jpg',
      brand: 'karen',
      isThai: true,
      category: 'bag',
      clearance: true,
      percentage: '30',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 43,
      name: 'Hmong 핸드메이트 빈티지 미니백',
      price: '29400',
      beforePrice: '42000',
      description: '세상 단 하나뿐인 예술 작품과도 같은 칸타퀼팅 핸드메이드 에스닉 미니 백',
      image: '19bag.jpg',
      hoverImage: '19-2bag.jpg',
      brand: 'Hmong',
      isThai: true,
      category: 'bag',
      clearance: true,
      percentage: '30',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 44,
      name: 'ORUMM 무로20 백팩_틸',
      price: '139000',
      beforePrice: '',
      description:
        '데일리로 메기도 좋고, 당인 산행이나 볼더링, 등반에도 가볍게 짐을 꾸릴 수 있는 ORUMM 20L 백팩',
      image: '20bag.jpg',
      hoverImage: '20-2bag.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 45,
      name: 'ORUMM 자루10 파우치 백',
      price: '39000',
      beforePrice: '',
      description: '일상 소지품부터 클라이밍 장비까지 거든하게 담는, 오름 업사이클 파우치 백',
      image: '21bag.jpg',
      hoverImage: '21-2bag.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 46,
      name: 'ORUMM 무로20 백팩_블루그레이',
      price: '139000',
      beforePrice: '',
      description:
        '데일리로 메기도 좋고, 당인 산행이나 볼더링, 등반에도 가볍게 짐을 꾸릴 수 있는 ORUMM 20L 백팩',
      image: '22bag.jpg',
      hoverImage: '22-2bag.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 47,
      name: 'ORUMM 워크아웃 메시 파우치',
      price: '28000',
      beforePrice: '',
      description:
        '각종 운동 및 물놀이 용품을 비롯해 다양한 소지품을 수납하기 좋은 오름의 파우치백',
      image: '23bag.jpg',
      hoverImage: '23-2bag.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'bag',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    // life
    {
      id: 48,
      name: '초경랑 인도어 슬리퍼',
      price: '3800',
      beforePrice: '4000',
      description: '탄력 EVA소재의 가볍고 편안한 다용도 슬리퍼(5colors)',
      image: '01life.jpg',
      hoverImage: '01-2life.jpg',
      brand: 'etc',
      isThai: false,
      category: 'life',
      clearance: false,
      percentage: '5',
      best: false,
      new: true,
      newSaleDate: '8.8',
    },
    {
      id: 49,
      name: 'PHUTAWAN 트로피칼 샤워젤 400ml_botanical delight',
      price: '20900',
      beforePrice: '22000',
      description: '인생 샤워젤이라고 할 수 있을 만큼, 풍부한 향의 샤워젤',
      image: '02life.jpg',
      hoverImage: '02-2life.jpg',
      brand: 'phutawan',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '5',
      best: true,
      new: true,
      newSaleDate: '8.8',
    },
    {
      id: 50,
      name: '간편한 보수 방충망 테이프',
      price: '3000',
      beforePrice: '',
      description: '간편하게 방춤망을 보수할 수 있는 강력한 접착력의 방충망 보수 테이프(2colors)',
      image: '03life.jpg',
      hoverImage: '03-2life.jpg',
      brand: 'etc',
      isThai: false,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 51,
      name: '알약 탈취제 2개 SET',
      price: '8000',
      beforePrice: '',
      description:
        '신발, 옷장 등 어디에서나 반영구적으로 사용가능한 향기로운 탈취, 방향제(2colors)',
      image: '04life.jpg',
      hoverImage: '04-2life.jpg',
      brand: 'etc',
      isThai: false,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 52,
      name: '포켓사이즈 암막 양우산',
      price: '10000',
      beforePrice: '',
      description: '작고 슬림하며 가벼워 휴대하기 좋은 한여름 필수템! 암막 양우산(4colors)',
      image: '05life.jpg',
      hoverImage: '05-2life.jpg',
      brand: 'etc',
      isThai: false,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 53,
      name: '머레이 급속냉각 핸디선풍기',
      price: '29000',
      beforePrice: '',
      description:
        '최대 13도까지 차가워지는 냉각바람 기능을 탑재한 핸디&탁상형 조절 가능한 만능 손풍기',
      image: '06life.jpg',
      hoverImage: '06-2life.jpg',
      brand: 'Murray',
      isThai: false,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 54,
      name: '녹지 않는 얼음 프로즌큐브 4P',
      price: '6000',
      beforePrice: '',
      description:
        '반영구적으로 사용가능하며, 인체에 무해한 재질로 제작된 음료 본연의 맛을 지킬 수 있는 스틸큐브 4p SET',
      image: '07life.jpg',
      hoverImage: '07-2life.jpg',
      brand: 'etc',
      isThai: false,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 55,
      name: 'INTREE 포어 미니마이징 스프레이 50ml',
      price: '48000',
      beforePrice: '',
      description: '푸타완의 플래그십 라인 Intree의 자연에서 온 깊은 치유력의 페이셜 스프레이',
      image: '08life.jpg',
      hoverImage: '08-2life.jpg',
      brand: 'phutawan',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 56,
      name: 'INTREE 안티에이징&재생 세럼 50ml',
      price: '52000',
      beforePrice: '',
      description: '푸타완의 플래그십 라이인 Intree 시리즈의 화학성분 없는 고기능성 세럼',
      image: '09life.jpg',
      hoverImage: '09-2life.jpg',
      brand: 'phutawan',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 57,
      name: 'PHUTAWAN 트로피컬 헤어 컨디셔너',
      price: '22000',
      beforePrice: '',
      description: '트로피컬 허브의 영양으로 모발을 촉촉하고 가볍게, 비건 헤어 컨티셔너_2types',
      image: '10life.jpg',
      hoverImage: '10-2life.jpg',
      brand: 'phutawan',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 58,
      name: 'SMELL lemongrass 쿨링 바디스프레이 60ml',
      price: '7000',
      beforePrice: '',
      description: '자연 에센셜 오일과 멘톨로 만든 60초만에 피부온도 8도를 낮추는 쿨링 스프레이',
      image: '11life.jpg',
      hoverImage: '11-2life.jpg',
      brand: 'smell',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 59,
      name: 'Just Modern 쿨링 헤어마스크',
      price: '6000',
      beforePrice: '',
      description: '건조하고 손상된 모발을 복원하며 시원함 가득 전할 기특한 모발용 마스크팩',
      image: '12life.jpg',
      hoverImage: '12-2life.jpg',
      brand: 'Just modurn',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 60,
      name: 'PHUTAWAN 모링가 리뉴얼&디펜스 에멀전',
      price: '39000',
      beforePrice: '',
      description:
        '모링가 오일과 화이트놀이 선사하는 고기능 진정 & 미백 에멀전. 민감성 피부도 안심히 사용하실 수 있어요',
      image: '14life.jpg',
      hoverImage: '14-2life.jpg',
      brand: 'phutawan',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 61,
      name: 'SMELL lemongrass 마사지 밤',
      price: '16000',
      beforePrice: '',
      description:
        '천연 레시피로 만든 부드러운 밤 타입 마사지제. 근육을 편안하게, 기분은 상쾌하게 바꿔드립니다.',
      image: '15life.jpg',
      hoverImage: '15-2life.jpg',
      brand: 'smell',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 62,
      name: 'PHUTAWAN 알로에베라 드롭 젤 99%',
      price: '12000',
      beforePrice: '',
      description: '천연 성분, 뛰어난 진정 및 보습 효과를 지닌 알로에베라 99% 피부 진정/보습 젤',
      image: '16life.jpg',
      hoverImage: '16-2life.jpg',
      brand: 'phutawan',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 63,
      name: 'SMELL lemongrass 모기퇴치 스프레이',
      price: '7500',
      beforePrice: '',
      description: 'DEET free 아이도 어른도 안심하고 쓰는 천연 유래 성분의 여름 필수템',
      image: '17life.jpg',
      hoverImage: '17-2life.jpg',
      brand: 'smell',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 64,
      name: 'SMELL lemongrass 에프터바이트 밤',
      price: '7500',
      beforePrice: '',
      description:
        '자연 유래 허브 성분으로 모기, 벌레물린 곳을 진정시켜 주는 작지만 든든한 여름철 필수템!',
      image: '18life.jpg',
      hoverImage: '18-2life.jpg',
      brand: 'smell',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 65,
      name: 'SMELL lemongrass 핸드메이드 비누-샌달우드',
      price: '8000',
      beforePrice: '',
      description: '스멜레몬그라스 사의 깊고 고요한 우디향, 샌달우드를 담은 핸드메이드 비누',
      image: '19life.jpg',
      hoverImage: '19-2life.jpg',
      brand: 'smell',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 66,
      name: 'POOMPUKSA 천연염색약-Dark brown',
      price: '8500',
      beforePrice: '',
      description:
        '완전한 천연성분으로 자극과 손상이 적으며 사용이 매우 간편한 스테디셀러 자가 염색약',
      image: '20life.jpg',
      hoverImage: '20-2life.jpg',
      brand: 'Poompuksa',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 67,
      name: 'POOMPUKSA 천연염색약-Light brown',
      price: '8500',
      beforePrice: '',
      description:
        '완전한 천연성분으로 자극과 손상이 적으며 사용이 매우 간편한 스테디셀러 자가 염색약',
      image: '211life.jpg',
      hoverImage: '21-2life.jpg',
      brand: 'Poompuksa',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 68,
      name: 'Wooden Kitchen Tools',
      price: '6000',
      beforePrice: '',
      description:
        '고품질의 우든웨어 제품들을 중간유통 없이 직접 제작처에서 매입해 합리적인 가격에 소개합니다.',
      image: '22life.jpg',
      hoverImage: '22-2life.jpg',
      brand: 'etc',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    {
      id: 69,
      name: '핸드메이드 라탄 티 코스터',
      price: '4000',
      beforePrice: '',
      description: '자연스러움과 감각적인 디자인이 어우러진 핸드메이드 티 코스터(6types)',
      image: '23life.jpg',
      hoverImage: '23-2life.jpg',
      brand: 'etc',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 70,
      name: 'Superpen',
      price: '36400',
      beforePrice: '52000',
      description: '나만의 오브제 자기부상 펜 하나로 계신 공간과 일상에 여유와 품격을 더해보세요',
      image: '24life.jpg',
      hoverImage: '24-2life.jpg',
      brand: 'etc',
      isThai: false,
      category: 'life',
      clearance: true,
      percentage: '30',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 71,
      name: 'PHUTAWAN 허벌 소프트바',
      price: '8000',
      beforePrice: '',
      description:
        '식물성 성분과 천연 오일로 만든 허브 비누. 피부를 정화하고 촉촉하게, 은은한 허브 향으로 상쾌한 하루를 선사합니다.',
      image: '19life.jpg',
      hoverImage: '19-2life.jpg',
      brand: 'phutawan',
      isThai: true,
      category: 'life',
      clearance: false,
      percentage: '',
      best: true,
      new: false,
      newSaleDate: '',
    },
    // 양말
    {
      id: 72,
      name: '에어핏 매쉬 페이크 삭스',
      price: '2000',
      beforePrice: '',
      description:
        '여름에도 쾌적하게, 발끝을 감싸는 가볍고 부드러운 스타킹 핏의 페이크 삭스(6colors)',
      image: '01socks.jpg',
      hoverImage: '01-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 73,
      name: 'Be On The Top 기능성 노쇼삭스',
      price: '2600',
      beforePrice: '',
      description: '하루 종일 쾌적함을 유지하는 고기능성 Dry-Cool 데일리 노쇼삭스(4colors)',
      image: '02socks.jpg',
      hoverImage: '02-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 74,
      name: 'CANDY SOCKS',
      price: '1800',
      beforePrice: '',
      description: '10가지 다양한 색상으로 준비한 스테디셀러 매쉬공법 쾌적한 베이직 발목양말',
      image: '03socks.jpg',
      hoverImage: '03-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 75,
      name: 'Lo mejor 노쇼삭스_BOLD',
      price: '2500',
      beforePrice: '',
      description: '베스트셀링 덧신양말 시리즈 Lo mejor의 5번째 버전(Men/Women/4colors)',
      image: '04socks.jpg',
      hoverImage: '04-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 76,
      name: '플라워&와플 노쇼삭스',
      price: '1600',
      beforePrice: '',
      description: '통기성 좋은 와플짜임으로 더욱 쾌적한 러블리 데일리 노쇼삭스(4colors)',
      image: '05socks.jpg',
      hoverImage: '05-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 77,
      name: '썸머 매쉬 노쇼삭스',
      price: '1600',
      beforePrice: '',
      description:
        '여름에도 발끝까지 시원하게! 발등 매쉬 디테일로 통기성을 살린 썸머 노쇼삭스(4colors)',
      image: '06socks.jpg',
      hoverImage: '06-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 78,
      name: '마린마크 삭스',
      price: '2200',
      beforePrice: '',
      description:
        '산뜻한 여름 감성과 시원한 착용감, 이 두 가지를 모두 담은 앵커자수 데일리 삭스(2colors)',
      image: '07socks.jpg',
      hoverImage: '07-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 79,
      name: 'Mono 노쇼삭스',
      price: '1800',
      beforePrice: '',
      description: '시원한 메쉬 포인트의 베이직 덧신양말(12colors)',
      image: '08socks.jpg',
      hoverImage: '08-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 80,
      name: '스마일베니 삭스',
      price: '3500',
      beforePrice: '',
      description: '스마일 엠블럼 자수 와펜 예쁘게 단 배색 디자인 발목양말(8colors)',
      image: '09socks.jpg',
      hoverImage: '09-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 81,
      name: '곰돌이와체크 노쇼삭스',
      price: '1800',
      beforePrice: '',
      description: '체커보드 위 곰돌이 귀여운 포인트의 여름용 노쇼삭스(4colors)',
      image: '10socks.jpg',
      hoverImage: '10-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 82,
      name: '맨즈 데일리안 삭스',
      price: '2000',
      beforePrice: '',
      description:
        '작지만 분명한 차이를 만드는 하루의ㅡ 기본, 사계용 스테디셀러 삭스(남성용, 3colors)',
      image: '11socks.jpg',
      hoverImage: '11-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 83,
      name: '데일리 코튼 로우삭스',
      price: '1200',
      beforePrice: '1500',
      description:
        '부드러운 순면 터치감과 심플한 디자인으로 매일 신어도 질리지 않는 데일리 로우삭스(4colors)',
      image: '12socks.jpg',
      hoverImage: '12-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 84,
      name: 'Affirmative 노쇼삭스',
      price: '1440',
      beforePrice: '1600',
      description:
        '숨겨두고 싶은 기분 좋은 비밀처럼, 발끝에 간직한 오늘의 긍정을 담은 노쇼삭스(6colors)',
      image: '13socks.jpg',
      hoverImage: '13-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 85,
      name: 'Saint 시스루 노쇼삭스',
      price: '2240',
      beforePrice: '2800',
      description:
        '산뜻한 착용감과 가볍게 흐르는 핏, 그리고 감각적인 Saint자수로 데일리 룩에 포인트를 더해줄 크루삭스(4colors)',
      image: '14socks.jpg',
      hoverImage: '14-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 86,
      name: '와일드 블룸 삭스',
      price: '1200',
      beforePrice: '1500',
      description:
        '사랑스러운 들꽃 자수와 시원한 착용감, 예쁘게 피어날 봄/여름을 완성해주는 양말(3colors)',
      image: '15socks.jpg',
      hoverImage: '15-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 87,
      name: '엔틱 페이즐리 크루삭스',
      price: '1440',
      beforePrice: '1800',
      description: '우아한 엔틱 페이즐리 패턴이 돋보이는 감성 가득한 사계절 양말(5colors)',
      image: '16socks.jpg',
      hoverImage: '16-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 88,
      name: '리본자수 와플 삭스',
      price: '1200',
      beforePrice: '1500',
      description:
        '디테일은 사랑스럽게, 착화감은 섬세하게! 당신의 봄과 여름을 위한 리본 와플삭스(4colors)',
      image: '17socks.jpg',
      hoverImage: '17-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 89,
      name: 'AEND 웨이브셔링 크루삭스',
      price: '3040',
      beforePrice: '3300',
      description:
        '자연스럽게 흐르는 물결처럼 발목을 감싸는 부드러운 셔링 디테일이 매력적인 크루삭스(3colors)',
      image: '18socks.jpg',
      hoverImage: '18-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 90,
      name: '블루 컨프레션 삭스',
      price: '1760',
      beforePrice: '2200',
      description: '파랑을 키워드로 감각적으로 풀어낸 캐주얼 무드의 긴 발목 양말(3colors)',
      image: '19socks.jpg',
      hoverImage: '19-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 91,
      name: '스마일 플라워 미드삭스',
      price: '1200',
      beforePrice: '1500',
      description:
        '발끝까지 기분 좋아지는 귀여운 키치 무드, 플라워, 스마일 자수가 사랑스럽게 포인트가 되어주는 데일리 삭스(3colors)',
      image: '20socks.jpg',
      hoverImage: '20-2socks.jpg',
      brand: 'etc',
      isThai: false,
      category: 'socks',
      clearance: true,
      percentage: '20',
      best: false,
      new: false,
      newSaleDate: '',
    },
    //패션템
    {
      id: 92,
      name: '콜렉터스캡_베리',
      price: '49000',
      beforePrice: '',
      description:
        '러닝, 하이킹, 클라이밍 등의 아웃동 활동시 좋을 가볍게 튼튼한 2가지 립소재를 믹스한 오름의 캠프캡입니다.',
      image: '01fashion.jpg',
      hoverImage: '01-2fashion.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'fashion',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 93,
      name: '콜렉터스캡_카키',
      price: '49000',
      beforePrice: '',
      description:
        '러닝, 하이킹, 클라이밍 등의 아웃동 활동시 좋을 가볍게 튼튼한 2가지 립소재를 믹스한 오름의 캠프캡입니다.',
      image: '02fashion.jpg',
      hoverImage: '02-2fashion.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'fashion',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 94,
      name: '콜렉터스캡_블랙',
      price: '49000',
      beforePrice: '',
      description:
        '러닝, 하이킹, 클라이밍 등의 아웃동 활동시 좋을 가볍게 튼튼한 2가지 립소재를 믹스한 오름의 캠프캡입니다.',
      image: '03fashion.jpg',
      hoverImage: '03-2fashion.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'fashion',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 95,
      name: 'ALWAYS ORUMM SAFETY BANDANA',
      price: '15000',
      beforePrice: '',
      description: '인수봉의 귀바위를 모티브로한 오름의 로고 반다나',
      image: '04fashion.jpg',
      hoverImage: '04-2fashion.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'fashion',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 96,
      name: '햄블파이 KEY WORD',
      price: '5600',
      beforePrice: '8000',
      description: '햄블파이만의 감성과 따뜻함이 담긴 한정판 키링 컬렉션 4종',
      image: '05fashion.jpg',
      hoverImage: '05-2fashion.jpg',
      brand: 'hamblepie',
      isThai: true,
      category: 'fashion',
      clearance: true,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '30',
    },
    {
      id: 97,
      name: '오름 6패널 버켓햇_머스타드',
      price: '42000',
      beforePrice: '',
      description: '봄, 여름, 가을 착용하기 좋은 편안한 착용감과 고기능성 원단의 ORUMM 버킷햇',
      image: '06fashion.jpg',
      hoverImage: '06-2fashion.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'fashion',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 98,
      name: '오름 6패널 버켓햇_살몬핑크',
      price: '42000',
      beforePrice: '',
      description: '봄, 여름, 가을 착용하기 좋은 편안한 착용감과 고기능성 원단의 ORUMM 버킷햇',
      image: '07fashion.jpg',
      hoverImage: '07-2fashion.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'fashion',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
    {
      id: 99,
      name: '오름 6패널 버켓햇_웨일',
      price: '42000',
      beforePrice: '',
      description: '봄, 여름, 가을 착용하기 좋은 편안한 착용감과 고기능성 원단의 ORUMM 버킷햇',
      image: '08fashion.jpg',
      hoverImage: '08-2fashion.jpg',
      brand: 'orumm',
      isThai: false,
      category: 'fashion',
      clearance: false,
      percentage: '',
      best: false,
      new: false,
      newSaleDate: '',
    },
  ]
}
